server:
  port: 8222
  servlet:
    context-path: /web

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    cache: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      max-file-size: 10MB
      max-request-size: 20MB
      resolve-lazily: false

  # 数据源配置
  datasource:
    username: root
    password: 123456
    #password: 3edc$ESZ
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.15.42.62:3306/demo?characterEncoding=utf8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    #type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    min: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

  redis:
    key:
      expire:
        phoneCode: 600 # 验证码超期时间
    host: 106.15.42.62  # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）

demo:
  file-upload :
    file-path: /data/file/
  permission:
    excludePath: /verificationCode,/login,/fileUpload/onlinePreview,/tcpService,/tcpCustom

aliy-ocr:
  appcode: b4f4f08c14234b158ed822de51f9147d
  invoice: #发票识别地址信息
    host: https://dgfp.market.alicloudapi.com
    path: /ocrservice/invoice

mybatis-plus:
  mapper-locations:
    - classpath*:/mapper/*.xml